import { expandedColumn } from '../ColumnGroups/ColumnGroups.module.css';

const headerConfiguration = {
    popTotalRank: { name: 'Total POP Rank', width: 75 },
    popTotal: { name: 'Total POP', width: 75 },
    twoPopTotal: { name: 'Total 2POP', width: 75 },
    ptlTotal: {
        name: 'Total PTL',
        width: 75,
        expandButton: true,
        expanded: false,
        onToggle: () => {},
    },
    popTotalPeak: { name: 'Peak Total Pop', width: 75 },
    popTotalPeakDate: { name: 'Peak Total Pop Date', width: 75 },
    unfTotal: { name: 'Total UNF', width: 75, addedStyle: expandedColumn },
    negTotal: { name: 'Total NEG', width: 75, addedStyle: expandedColumn },
    ddlTotal: { name: 'Total DDL', width: 75, addedStyle: expandedColumn },
    nopTotal: { name: 'Total NOP', width: 75, addedStyle: expandedColumn },
    favTotal: { name: 'Total FAV', width: 75, addedStyle: expandedColumn },
    likTotal: { name: 'Total LIK', width: 75, addedStyle: expandedColumn },
    popCoreRank: { name: 'Core Pop Rank', width: 75 },
    popCore: { name: 'Core Pop', width: 75 },
    twoPopCore: { name: 'Core 2POP', width: 75 },
    ptlCore: {
        name: 'Core PTL',
        width: 75,
        expandButton: true,
        expanded: false,
        onToggle: () => {},
    },
    unfCore: { name: 'Core UNF', width: 75, addedStyle: expandedColumn },
    negCore: { name: 'Core NEG', width: 75, addedStyle: expandedColumn },
    ddlCore: { name: 'Core DDL', width: 75, addedStyle: expandedColumn },
    nopCore: { name: 'Core NOP', width: 75, addedStyle: expandedColumn },
    favCore: { name: 'Core FAV', width: 75, addedStyle: expandedColumn },
    likCore: { name: 'Core LIK', width: 75, addedStyle: expandedColumn },
    popAa: { name: 'African American POP', width: 75 },
    twoPopAa: { name: 'African American 2POP', width: 75 },
    ptlAa: { name: 'African American PTL', width: 75 },
    popHispanic: { name: 'Hispanic POP', width: 75 },
    twoPopHispanic: { name: 'Hispanic 2POP', width: 75 },
    ptlHispanic: { name: 'Hispanic PTL', width: 75 },
    popAaHisp: { name: 'African American/Hispanic POP', width: 130 },
    twoPopAaHisp: { name: 'African American/Hispanic 2POP', width: 130 },
    ptlAaHisp: { name: 'African American/Hispanic PTL', width: 130 },
    popWhite: { name: 'White POP', width: 75 },
    twoPopWhite: { name: 'White 2POP', width: 75 },
    ptlWhite: { name: 'White PTL', width: 75 },
    popAsian: { name: 'Asian POP', width: 75 },
    twoPopAsian: { name: 'Asian 2POP', width: 75 },
    ptlAsian: { name: 'Asian PTL', width: 75 },
    popMale: { name: 'Male POP', width: 75 },
    twoPopMale: { name: 'Male 2POP', width: 75 },
    ptlMale: { name: 'Male PTL', width: 75 },
    popFemale: { name: 'Female POP', width: 75 },
    twoPopFemale: { name: 'Female 2POP', width: 75 },
    ptlFemale: { name: 'Female PTL', width: 75 },
    popYoung: { name: 'Young POP', width: 75 },
    twoPopYoung: { name: 'Young 2POP', width: 75 },
    ptlYoung: { name: 'Young PTL', width: 75 },
    popOld: { name: 'Old POP', width: 75 },
    twoPopOld: { name: 'Old 2POP', width: 75 },
    ptlOld: { name: 'Old PTL', width: 75 },
    popTotalConsolidated1Rank: { name: 'CHR Consolidated 1 Total POP Rank', width: 110 },
    popTotalConsolidated1: { name: 'CHR Consolidated 1 Total POP', width: 110 },
    popTotalConsolidated2Rank: { name: 'CHR Consolidated 2 Total POP Rank', width: 110 },
    popTotalConsolidated2: { name: 'CHR Consolidated 2 Total POP', width: 110 },
    popTotalConsolidated3Rank: { name: 'CHR Consolidated 3 Total POP Rank', width: 110 },
    popTotalConsolidated3: { name: 'CHR Consolidated 3 Total POP', width: 110 },
};

export default headerConfiguration;
