// ****************** 3 things needed: all groups and columns, default setup, and preferenced setup ****************

export const allGroupsAndColumns = {
    columnGroups: [
        'songInfo',
        'categories',
        'crg',
        'taa',
        'callout',
        'spins',
        'mScore',
        'iHeartDigital',
        'hitPredictor',
    ],
    columns: {
        songInfo: ['titleArtist', 'version'],
        categories: ['prior', 'current', 'new', 'recommended'],
        crg: ['crg'],
        taa: ['taaRank', 'taa', 'plus100', 'plus300'],
        callout: [
            'popTotalRank',
            'popTotal',
            'twoPopTotal',
            'ptlTotal',
            'popTotalPeak',
            'popTotalPeakDate',
            'unfTotal',
            'negTotal',
            'ddlTotal',
            'nopTotal',
            'favTotal',
            'likTotal',
            'popCoreRank',
            'popCore',
            'twoPopCore',
            'ptlCore',
            'unfCore',
            'negCore',
            'ddlCore',
            'nopCore',
            'favCore',
            'likCore',
            'popAa',
            'twoPopAa',
            'ptlAa',
            'popHispanic',
            'twoPopHispanic',
            'ptlHispanic',
            'popAaHisp',
            'twoPopAaHisp',
            'ptlAaHisp',
            'popWhite',
            'twoPopWhite',
            'ptlWhite',
            'popAsian',
            'twoPopAsian',
            'ptlAsian',
            'popMale',
            'twoPopMale',
            'ptlMale',
            'popFemale',
            'twoPopFemale',
            'ptlFemale',
            'popYoung',
            'twoPopYoung',
            'ptlYoung',
            'popOld',
            'twoPopOld',
            'ptlOld',
            'popTotalConsolidated1Rank',
            'popTotalConsolidated1',
            'popTotalConsolidated2Rank',
            'popTotalConsolidated2',
            'popTotalConsolidated3Rank',
            'popTotalConsolidated3',
        ],
        customConsolidatedCallout: [
            'popTotalRank',
            'popTotal',
            'twoPopTotal',
            'ptlTotal',
            'popTotalPeak',
            'popTotalPeakDate',
            'unfTotal',
            'negTotal',
            'ddlTotal',
            'nopTotal',
            'favTotal',
            'likTotal',
            'popCoreRank',
            'popCore',
            'twoPopCore',
            'ptlCore',
            'unfCore',
            'negCore',
            'ddlCore',
            'nopCore',
            'favCore',
            'likCore',
            'popAa',
            'twoPopAa',
            'ptlAa',
            'popHispanic',
            'twoPopHispanic',
            'ptlHispanic',
            'popAaHisp',
            'twoPopAaHisp',
            'ptlAaHisp',
            'popWhite',
            'twoPopWhite',
            'ptlWhite',
            'popAsian',
            'twoPopAsian',
            'ptlAsian',
            'popMale',
            'twoPopMale',
            'ptlMale',
            'popFemale',
            'twoPopFemale',
            'ptlFemale',
            'popYoung',
            'twoPopYoung',
            'ptlYoung',
            'popOld',
            'twoPopOld',
            'ptlOld',
            'popTotalConsolidated1Rank',
            'popTotalConsolidated1',
            'popTotalConsolidated2Rank',
            'popTotalConsolidated2',
            'popTotalConsolidated3Rank',
            'popTotalConsolidated3',
        ],
        omt: [
            'popTotalRank',
            'popTotal',
            'twoPopTotal',
            'ptlTotal',
            'popTotalPeak',
            'popTotalPeakDate',
            'unfTotal',
            'negTotal',
            'ddlTotal',
            'nopTotal',
            'favTotal',
            'likTotal',
            'popCoreRank',
            'popCore',
            'twoPopCore',
            'ptlCore',
            'unfCore',
            'negCore',
            'ddlCore',
            'nopCore',
            'favCore',
            'likCore',
            'popAa',
            'twoPopAa',
            'ptlAa',
            'popHispanic',
            'twoPopHispanic',
            'ptlHispanic',
            'popAaHisp',
            'twoPopAaHisp',
            'ptlAaHisp',
            'popWhite',
            'twoPopWhite',
            'ptlWhite',
            'popAsian',
            'twoPopAsian',
            'ptlAsian',
            'popMale',
            'twoPopMale',
            'ptlMale',
            'popFemale',
            'twoPopFemale',
            'ptlFemale',
            'popYoung',
            'twoPopYoung',
            'ptlYoung',
            'popOld',
            'twoPopOld',
            'ptlOld',
            'popTotalConsolidated1Rank',
            'popTotalConsolidated1',
            'popTotalConsolidated2Rank',
            'popTotalConsolidated2',
            'popTotalConsolidated3Rank',
            'popTotalConsolidated3',
        ],
        customConsolidatedOmt: [
            'popTotalRank',
            'popTotal',
            'twoPopTotal',
            'ptlTotal',
            'popTotalPeak',
            'popTotalPeakDate',
            'unfTotal',
            'negTotal',
            'ddlTotal',
            'nopTotal',
            'favTotal',
            'likTotal',
            'popCoreRank',
            'popCore',
            'twoPopCore',
            'ptlCore',
            'unfCore',
            'negCore',
            'ddlCore',
            'nopCore',
            'favCore',
            'likCore',
            'popAa',
            'twoPopAa',
            'ptlAa',
            'popHispanic',
            'twoPopHispanic',
            'ptlHispanic',
            'popAaHisp',
            'twoPopAaHisp',
            'ptlAaHisp',
            'popWhite',
            'twoPopWhite',
            'ptlWhite',
            'popAsian',
            'twoPopAsian',
            'ptlAsian',
            'popMale',
            'twoPopMale',
            'ptlMale',
            'popFemale',
            'twoPopFemale',
            'ptlFemale',
            'popYoung',
            'twoPopYoung',
            'ptlYoung',
            'popOld',
            'twoPopOld',
            'ptlOld',
            'popTotalConsolidated1Rank',
            'popTotalConsolidated1',
            'popTotalConsolidated2Rank',
            'popTotalConsolidated2',
            'popTotalConsolidated3Rank',
            'popTotalConsolidated3',
        ],
        spins: [
            'spins6am7pm',
            'spins6am12m',
            'spins24Hr',
            'totalStationSpins24Hr',
            'marketSpins24Hr',
            'totalMarketSpins24Hr',
            'peakChartPosition',
            'peakChartDate',
            'peakSpins',
            'peakSpinsDate',
        ],
        mScore: ['mScore', 'playcount', 'switchWeek1', 'switchWeek2', 'switchWeek3', 'switchWeek4'],
        iHeartDigital: ['thumbsUp%', 'thumbsDown%', 'completed'],
        hitPredictor: ['score'],
    },
};

export const defaultSetup = {
    columnGroups: [
        'songInfo',
        'categories',
        'crg',
        'taa',
        'callout',
        'customConsolidatedCallout',
        'omt',
        'customConsolidatedOmt',
        'spins',
        'mscore',
        'iHeartDigital',
        'hitPredictor',
    ],
    columns: {
        songInfo: ['titleArtist'],
        categories: ['prior', 'current', 'new', 'recommended'],
        crg: ['crg'],
        taa: ['taaRank', 'taa'],
        callout: ['totalPopRank', 'totalPop', 'total2Pop', 'totalPtl', 'corePopRank', 'corePop', 'core2Pop', 'corePtl'],
        customConsolidatedCallout: ['totalPopRank', 'totalPop', 'corePopRank', 'corePop'],
        omt: ['totalPopRank', 'totalPop', 'corePopRank', 'corePop'],
        customConsolidatedOmt: ['totalPopRank', 'totalPop', 'corePopRank', 'corePop'],
        spins: [
            'spins6am7pm',
            'spins6am12m',
            'spins24Hr',
            'totalStationSpins24Hr',
            'marketSpins24Hr',
            'totalMarketSpins24Hr',
        ],
        mScore: ['mScore', 'playcount', 'switchWeek1', 'switchWeek2', 'switchWeek3', 'switchWeek4'],
        iHeartDigital: ['thumbsUp%', 'thumbsDown%', 'completed'],
        hitPredictor: ['score'],
    },
};
