// If anything gets added or removed from the groups or items, update the order
// properties to prevent errors on musictracker and customize table modal
export default [
    {
        id: 1,
        order: 1,
        label: 'Song Information',
        key: 'songInformation',
        fixed: true,
        itemsDraggable: false,
        items: [
            {
                id: 201,
                label: 'Checkbox',
                order: 1,
                sortKey: 'checked',
                checked: true,
                disabled: true,
            },
            {
                id: 1,
                label: 'Title/Artist',
                order: 2,
                sortKey: 'sNm',
                checked: true,
                disabled: true,
            },
            {
                id: 2,
                label: 'Version',
                order: 3,
                sortKey: 'versionName',
                checked: false,
            },
        ],
    },
    {
        id: 2,
        order: 2,
        key: 'category',
        label: 'Category',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Prior',
                order: 1,
                sortKey: 'category.prior',
                checked: true,
            },
            {
                id: 2,
                label: 'Current',
                order: 2,
                sortKey: 'category.current',
                checked: true,
            },
            {
                id: 3,
                label: 'Recommended',
                order: 3,
                sortKey: 'category.recommended',
                checked: false,
                hidden: false,
            },
            {
                id: 4,
                label: 'New',
                order: 4,
                sortKey: 'category.staged',
                checked: true,
            },
        ],
    },
    {
        id: 3,
        order: 3,
        key: 'crg',
        label: 'CRG',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'CRG',
                order: 1,
                sortKey: 'crg',
                checked: true,
            },
        ],
    },
    {
        id: 4,
        order: 4,
        key: 'enhanced',
        label: 'TAA',
        itemsDraggable: true,
        items: [
            {
                id: 100,
                label: 'TAA Rank',
                order: 1,
                sortKey: 'enhanced.pop.rnk',
                checked: true,
            },
            {
                id: 102,
                label: 'TAA',
                order: 2,
                sortKey: 'enhanced.pop.num',
                checked: true,
            },
            {
                // this is data we are not currently using
                id: 104,
                label: 'Local Tier',
                order: 3,
                sortKey: 'enhanced.localTier.number',
                checked: false,
                hidden: true,
            },
            {
                id: 4,
                label: 'Local Tier Name',
                order: 4,
                sortKey: 'enhanced.localTier.name',
                checked: false,
                hidden: true,
            },
            {
                id: 5,
                label: 'National Tier',
                order: 5,
                sortKey: 'enhanced.nationalTier.number',
                checked: false,
                hidden: true,
            },
            {
                id: 6,
                label: 'National Tier Name',
                order: 6,
                sortKey: 'enhanced.nationalTier.name',
                checked: false,
                hidden: true,
            },
            {
                id: 7,
                label: '+100',
                order: 7,
                sortKey: 'enhanced.plus100.spins',
                checked: false,
            },
            {
                id: 8,
                label: '+300',
                order: 8,
                sortKey: 'enhanced.plus300.spins',
                checked: false,
            },
        ],
    },
    {
        id: 5,
        order: 5,
        key: 'callout',
        label: 'Callout',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Total POP Rank',
                order: 1,
                sortKey: 'callout.pop.tRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 2,
                label: 'Total POP',
                order: 2,
                sortKey: 'callout.pop.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 3,
                label: 'Total 2Pop',
                order: 3,
                sortKey: 'callout.2pop.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 4,
                label: 'Total PTL',
                order: 4,
                sortKey: 'callout.ptl.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 5,
                label: 'Peak Total Pop',
                order: 5,
                sortKey: 'callout.pop.tPeakScore',
                checked: false,
            },
            {
                id: 6,
                label: 'Peak Total Pop Date',
                order: 6,
                sortKey: 'callout.pop.tPeakDt',
                checked: false,
            },
            {
                id: 7,
                label: 'Total UNF',
                order: 7,
                sortKey: 'callout.unf.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 8,
                label: 'Total NEG',
                order: 8,
                sortKey: 'callout.neg.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 9,
                label: 'Total DDL',
                order: 9,
                sortKey: 'callout.ddl.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 10,
                label: 'Total NOP',
                order: 10,
                sortKey: 'callout.nop.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 11,
                label: 'Total LIK',
                order: 11,
                sortKey: 'callout.lik.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 12,
                label: 'Total FAV',
                order: 12,
                sortKey: 'callout.fav.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 13,
                label: 'Core Pop Rank',
                order: 13,
                sortKey: 'callout.pop.cRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 14,
                label: 'Core Pop',
                order: 14,
                sortKey: 'callout.pop.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 15,
                label: 'Core 2Pop',
                order: 15,
                sortKey: 'callout.2pop.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 16,
                label: 'Core PTL',
                order: 16,
                sortKey: 'callout.ptl.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 17,
                label: 'Core UNF',
                order: 17,
                sortKey: 'callout.unf.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 18,
                label: 'Core NEG',
                order: 18,
                sortKey: 'callout.neg.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 19,
                label: 'Core DDL',
                order: 19,
                sortKey: 'callout.ddl.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 20,
                label: 'Core NOP',
                order: 20,
                sortKey: 'callout.nop.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 21,
                label: 'Core LIK',
                order: 21,
                sortKey: 'callout.lik.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 22,
                label: 'Core FAV',
                order: 22,
                sortKey: 'callout.fav.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 23,
                label: 'African American POP',
                order: 23,
                sortKey: 'callout.pop.aa',
                checked: false,
                hasTrends: true,
            },
            {
                id: 24,
                label: 'African American 2POP',
                order: 24,
                sortKey: 'callout.2pop.aa',
                checked: false,
                hasTrends: true,
            },
            {
                id: 25,
                label: 'African American PTL',
                order: 25,
                sortKey: 'callout.ptl.aa',
                checked: false,
                hasTrends: true,
            },
            {
                id: 26,
                label: 'Hispanic POP',
                order: 26,
                sortKey: 'callout.pop.hisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 27,
                label: 'Hispanic 2POP',
                order: 27,
                sortKey: 'callout.2pop.hisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 28,
                label: 'Hispanic PTL',
                order: 28,
                sortKey: 'callout.ptl.hisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 29,
                label: 'African American/Hispanic POP',
                order: 29,
                sortKey: 'callout.pop.aahisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 30,
                label: 'African American/Hispanic 2POP',
                order: 30,
                sortKey: 'callout.2pop.aahisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 31,
                label: 'African American/Hispanic PTL',
                order: 31,
                sortKey: 'callout.ptl.aahisp',
                checked: false,
                hasTrends: true,
            },
            {
                id: 32,
                label: 'White POP',
                order: 32,
                sortKey: 'callout.pop.white',
                checked: false,
                hasTrends: true,
            },
            {
                id: 33,
                label: 'White 2POP',
                order: 33,
                sortKey: 'callout.2pop.white',
                checked: false,
                hasTrends: true,
            },
            {
                id: 34,
                label: 'White PTL',
                order: 34,
                sortKey: 'callout.ptl.white',
                checked: false,
                hasTrends: true,
            },
            {
                id: 35,
                label: 'Asian POP',
                order: 35,
                sortKey: 'callout.pop.asian',
                checked: false,
                hasTrends: true,
            },
            {
                id: 36,
                label: 'Asian 2POP',
                order: 36,
                sortKey: 'callout.2pop.asian',
                checked: false,
                hasTrends: true,
            },
            {
                id: 37,
                label: 'Asian PTL',
                order: 37,
                sortKey: 'callout.ptl.asian',
                checked: false,
                hasTrends: true,
            },
            {
                id: 38,
                label: 'Male POP',
                order: 38,
                sortKey: 'callout.pop.male',
                checked: false,
                hasTrends: true,
            },
            {
                id: 39,
                label: 'Male 2POP',
                order: 39,
                sortKey: 'callout.2pop.male',
                checked: false,
                hasTrends: true,
            },
            {
                id: 40,
                label: 'Male PTL',
                order: 40,
                sortKey: 'callout.ptl.male',
                checked: false,
                hasTrends: true,
            },
            {
                id: 41,
                label: 'Female POP',
                order: 41,
                sortKey: 'callout.pop.female',
                checked: false,
                hasTrends: true,
            },
            {
                id: 42,
                label: 'Female 2POP',
                order: 42,
                sortKey: 'callout.2pop.female',
                checked: false,
                hasTrends: true,
            },
            {
                id: 43,
                label: 'Female PTL',
                order: 43,
                sortKey: 'callout.ptl.female',
                checked: false,
                hasTrends: true,
            },
            {
                id: 44,
                label: 'Young POP',
                order: 44,
                sortKey: 'callout.pop.young',
                checked: false,
                hasTrends: true,
            },
            {
                id: 45,
                label: 'Young 2POP',
                order: 45,
                sortKey: 'callout.2pop.young',
                checked: false,
                hasTrends: true,
            },
            {
                id: 46,
                label: 'Young PTL',
                order: 46,
                sortKey: 'callout.ptl.young',
                checked: false,
                hasTrends: true,
            },
            {
                id: 47,
                label: 'Old POP',
                order: 47,
                sortKey: 'callout.pop.old',
                checked: false,
                hasTrends: true,
            },
            {
                id: 48,
                label: 'Old 2POP',
                order: 48,
                sortKey: 'callout.2pop.old',
                checked: false,
                hasTrends: true,
            },
            {
                id: 49,
                label: 'Old PTL',
                order: 49,
                sortKey: 'callout.ptl.old',
                checked: false,
                hasTrends: true,
            },
            {
                id: 50,
                label: 'Consolidated 1 Total POP Rank',
                order: 50,
                sortKey: 'callout.pop.consolidated1TotalRank',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
            {
                id: 51,
                label: 'Consolidated 1 Total POP',
                order: 51,
                sortKey: 'callout.pop.consolidated1Total',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
            {
                id: 52,
                label: 'Consolidated 2 Total POP Rank',
                order: 52,
                sortKey: 'callout.pop.consolidated2TotalRank',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
            {
                id: 53,
                label: 'Consolidated 2 Total POP',
                order: 53,
                sortKey: 'callout.pop.consolidated2Total',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
            {
                id: 54,
                label: 'Consolidated 3 Total POP Rank',
                order: 54,
                sortKey: 'callout.pop.consolidated3TotalRank',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
            {
                id: 55,
                label: 'Consolidated 3 Total POP',
                order: 55,
                sortKey: 'callout.pop.consolidated3Total',
                checked: false,
                hasTrends: false,
                hidden: false,
            },
        ],
    },
    {
        id: 6,
        order: 6,
        key: 'customCallout',
        label: 'Custom Consolidated Callout',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Total POP Rank',
                order: 1,
                sortKey: 'customCallout.pop.tRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 2,
                label: 'Total POP',
                order: 2,
                sortKey: 'customCallout.pop.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 3,
                label: 'Total 2Pop',
                order: 3,
                sortKey: 'customCallout.2pop.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 4,
                label: 'Total PTL',
                order: 4,
                sortKey: 'customCallout.ptl.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 5,
                label: 'Core Pop Rank',
                order: 5,
                sortKey: 'customCallout.pop.cRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 6,
                label: 'Core Pop',
                order: 6,
                sortKey: 'customCallout.pop.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 7,
                label: 'Core 2Pop',
                order: 7,
                sortKey: 'customCallout.2pop.score',
                checked: false,
                hasTrends: true,
            },
            {
                id: 8,
                label: 'Core PTL',
                order: 8,
                sortKey: 'customCallout.ptl.score',
                checked: false,
                hasTrends: true,
            },
        ],
    },
    {
        id: 7,
        order: 7,
        key: 'omt',
        label: 'OMT',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Total POP Rank',
                order: 1,
                sortKey: 'omt.pop.tRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 2,
                label: 'Total POP',
                order: 2,
                sortKey: 'omt.pop.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 3,
                label: 'Total 2Pop',
                order: 3,
                sortKey: 'omt.2pop.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 4,
                label: 'Total PTL',
                order: 4,
                sortKey: 'omt.ptl.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 7,
                label: 'Total UNF',
                order: 7,
                sortKey: 'omt.unf.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 8,
                label: 'Total NEG',
                order: 8,
                sortKey: 'omt.neg.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 9,
                label: 'Total DDL',
                order: 9,
                sortKey: 'omt.ddl.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 10,
                label: 'Total NOP',
                order: 10,
                sortKey: 'omt.nop.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 11,
                label: 'Total LIK',
                order: 11,
                sortKey: 'omt.lik.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 12,
                label: 'Total FAV',
                order: 12,
                sortKey: 'omt.fav.total',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 13,
                label: 'Core Pop Rank',
                order: 13,
                sortKey: 'omt.pop.cRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 14,
                label: 'Core Pop',
                order: 14,
                sortKey: 'omt.pop.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 15,
                label: 'Core 2Pop',
                order: 15,
                sortKey: 'omt.2pop.score',
                checked: false,
                hasTrends: true,
            },
            {
                id: 16,
                label: 'Core PTL',
                order: 16,
                sortKey: 'omt.ptl.score',
                checked: false,
                hasTrends: true,
            },
            {
                id: 17,
                label: 'Core UNF',
                order: 17,
                sortKey: 'omt.unf.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 18,
                label: 'Core NEG',
                order: 18,
                sortKey: 'omt.neg.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 19,
                label: 'Core DDL',
                order: 19,
                sortKey: 'omt.ddl.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 20,
                label: 'Core NOP',
                order: 20,
                sortKey: 'omt.nop.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 21,
                label: 'Core LIK',
                order: 21,
                sortKey: 'omt.lik.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
            {
                id: 22,
                label: 'Core FAV',
                order: 22,
                sortKey: 'omt.fav.score',
                checked: true,
                hasTrends: true,
                disabled: true,
                hidden: false,
            },
        ],
    },
    {
        id: 8,
        order: 8,
        key: 'customOmt',
        label: 'Custom Consolidated OMT',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Total POP Rank',
                order: 1,
                sortKey: 'customOmt.pop.tRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 2,
                label: 'Total POP',
                order: 2,
                sortKey: 'customOmt.pop.total',
                checked: true,
                hasTrends: true,
            },
            {
                id: 3,
                label: 'Total 2Pop',
                order: 3,
                sortKey: 'customOmt.2pop.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 4,
                label: 'Total PTL',
                order: 4,
                sortKey: 'customOmt.ptl.total',
                checked: false,
                hasTrends: true,
            },
            {
                id: 5,
                label: 'Core Pop Rank',
                order: 5,
                sortKey: 'customOmt.pop.cRnk',
                checked: true,
                hasTrends: true,
            },
            {
                id: 6,
                label: 'Core Pop',
                order: 6,
                sortKey: 'customOmt.pop.score',
                checked: true,
                hasTrends: true,
            },
            {
                id: 7,
                label: 'Core 2Pop',
                order: 7,
                sortKey: 'customOmt.2pop.score',
                checked: false,
                hasTrends: true,
            },
            {
                id: 8,
                label: 'Core PTL',
                order: 8,
                sortKey: 'customOmt.ptl.score',
                checked: false,
                hasTrends: true,
            },
        ],
    },
    {
        id: 9,
        order: 9,
        key: 'spins',
        label: 'Spins',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Competitor Spins',
                order: 1,
                sortKey: 'spins.competitor',
                customCategoryComponent: 'CompetitorSpins',
                selectedCompetitors: [],
                columnType: 'competitors',
            },
            {
                id: 2,
                label: 'Spins 6AM-7PM',
                order: 2,
                sortKey: 'spins.6am7pm',
                checked: true,
            },
            {
                id: 3,
                label: 'Spins 6AM-12M',
                order: 3,
                sortKey: 'spins.6a12m',
                checked: true,
            },
            {
                id: 4,
                label: 'Spins 24HR',
                order: 4,
                sortKey: 'spins.24hr',
                checked: true,
            },
            {
                id: 5,
                label: 'Total Station Spins 24HR',
                order: 5,
                sortKey: 'spins.totalStn',
                checked: true,
            },
            {
                id: 6,
                label: 'Market Spins 24HR',
                order: 6,
                sortKey: 'spins.mrkt',
                checked: true,
            },
            {
                id: 7,
                label: 'Total Market Spins 24HR',
                order: 7,
                sortKey: 'spins.totalMrkt',
                checked: true,
            },
            {
                id: 8,
                label: 'Peak Chart Position',
                order: 8,
                sortKey: 'spins.peakChartPos',
                checked: false,
            },
            {
                id: 9,
                label: 'Peak Chart Date',
                order: 9,
                sortKey: 'spins.peakChartDt',
                checked: false,
            },
            {
                id: 10,
                label: 'Peak Spins',
                order: 10,
                sortKey: 'spins.peak',
                checked: false,
            },
            {
                id: 11,
                label: 'Peak Spins Date',
                order: 11,
                sortKey: 'spins.peakSpinsDt',
                checked: false,
            },
            {
                id: 12,
                labelTemplate: '{callLetters} Spins 6AM-7PM',
                label: '',
                order: 12,
                sortKey: 'spins.competitor1.6am7pm',
                checked: true,
                hidden: true,
                competitorOrder: 1,
                columnType: 'competitors',
            },
            {
                id: 13,
                labelTemplate: '{callLetters} Spins 6AM-12M',
                label: '',
                order: 13,
                sortKey: 'spins.competitor1.6am12m',
                checked: true,
                hidden: true,
                competitorOrder: 1,
                columnType: 'competitors',
            },
            {
                id: 14,
                labelTemplate: '{callLetters} Spins 24HR',
                label: '',
                order: 14,
                sortKey: 'spins.competitor1.24hr',
                checked: true,
                hidden: true,
                competitorOrder: 1,
                columnType: 'competitors',
            },
            {
                id: 15,
                labelTemplate: '{callLetters} Spins 6AM-7PM',
                label: '',
                order: 15,
                sortKey: 'spins.competitor2.6am7pm',
                checked: true,
                hidden: true,
                competitorOrder: 2,
                columnType: 'competitors',
            },
            {
                id: 16,
                labelTemplate: '{callLetters} Spins 6AM-12M',
                label: '',
                order: 16,
                sortKey: 'spins.competitor2.6am12m',
                checked: true,
                hidden: true,
                competitorOrder: 2,
                columnType: 'competitors',
            },
            {
                id: 17,
                labelTemplate: '{callLetters} Spins 24HR',
                label: '',
                order: 17,
                sortKey: 'spins.competitor2.24hr',
                checked: true,
                hidden: true,
                competitorOrder: 2,
                columnType: 'competitors',
            },
        ],
    },
    {
        id: 10,
        order: 10,
        key: 'mscore',
        label: 'Mscore',
        itemsDraggable: true,
        items: [
            {
                id: 15,
                label: 'Mscore',
                order: 1,
                sortKey: 'mscore.switching',
                checked: true,
            },
            {
                id: 16,
                label: 'Playcount',
                order: 2,
                sortKey: 'mscore.plyCount',
                checked: true,
            },
            {
                id: 116,
                label: 'Switch Week 1',
                order: 3,
                sortKey: 'mscore.sWeek1',
                checked: true,
            },
            {
                id: 117,
                label: 'Switch Week 2',
                order: 4,
                sortKey: 'mscore.sWeek2',
                checked: true,
            },
            {
                id: 118,
                label: 'Switch Week 3',
                order: 5,
                sortKey: 'mscore.sWeek3',
                checked: true,
            },
            {
                id: 119,
                label: 'Switch Week 4',
                order: 6,
                sortKey: 'mscore.sWeek4',
                checked: true,
            },
        ],
    },
    {
        id: 11,
        order: 11,
        key: 'iHeartDigital',
        label: 'iHeart Digital',
        itemsDraggable: true,
        items: [
            {
                id: 1,
                label: 'Thumbs Up %',
                order: 1,
                sortKey: 'iHeartDigital.thumbsUp',
                checked: true,
            },
            {
                id: 2,
                label: 'Thumbs Down %',
                order: 2,
                sortKey: 'iHeartDigital.thumbsDown',
                checked: true,
            },
            {
                id: 3,
                label: 'Completed',
                order: 3,
                sortKey: 'iHeartDigital.completed',
                checked: true,
            },
        ],
    },
    {
        id: 12,
        order: 12,
        key: 'hitPredictor',
        label: 'Hit Predictor',
        itemsDraggable: true,
        items: [
            {
                id: 17,
                label: 'Score',
                order: 2,
                sortKey: 'hitPredictor.score',
                checked: true,
            },
        ],
    },
];
