// board details
export const REQUEST_BOARD = 'REQUEST_BOARD';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const THROW_BOARD = 'THROW_BOARD';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const SET_HOSTINFO = 'SET_HOSTINFO';

// user board
export const FETCH_ALL_TEAMS_SUCCESS = 'FETCH_ALL_TEAMS_SUCCESS';
export const FETCH_ALL_USERS_SUCCESS = 'FETCH_ALL_USERS_SUCCESS';
export const USERS_LOADING = 'USERS_LOADING';

// dayparts
export const DAYPART_PENDING = 'DAYPART_PENDING';
export const DAYPART_SUCCESS = 'DAYPART_SUCCESS';
export const DAYPART_FAILURE = 'DAYPART_FAILURE';
export const CREATE_DAYPART_SUCCESS = 'CREATE_DAYPART_SUCCESS';
export const EDIT_DAYPART_SUCCESS = 'EDIT_DAYPART_SUCCESS';
export const DAYPART_UPDATE_STAGED_DATA = 'DAYPART_UPDATE_STAGED_DATA';
export const CLEAR_STAGED_DAYPART_CHANGES = 'CLEAR_STAGED_DAYPART_CHANGES';

// recommendable categories
export const STORE_RECOMMENDABLE_CATEGORIES = 'STORE_RECOMMENDABLE_CATEGORIES';
export const HIDE_RECOMMENDABLE_CATEGORIES = 'HIDE_RECOMMENDABLE_CATEGORIES';

// box
export const BOX_PENDING = 'BOX_PENDING';
export const BOX_CLEARED_SUCCESS = 'BOX_CLEARED_SUCCESS';
export const BOX_FAILURE = 'BOX_FAILURE';
export const BOX_OPEN_SUCCESS = 'BOX_OPEN_SUCCESS';
export const BOX_CLOSED_SUCCESS = 'BOX_CLOSED_SUCCESS';

// restrictions
export const RESTRICTION_PENDING = 'RESTRICTION_PENDING';
export const RESTRICTION_SUCCESS = 'RESTRICTION_SUCCESS';
export const RESTRICTION_FAILURE = 'RESTRICTION_FAILURE';
export const RESTRICTION_UPDATE_STAGED_DATA = 'RESTRICTION_UPDATE_STAGED_DATA';
export const CREATE_RESTRICTION_SUCCESS = 'CREATE_RESTRICTION_SUCCESS';
export const EDIT_RESTRICTION_SUCCESS = 'EDIT_RESTRICTION_SUCCESS';
export const CLEAR_STAGED_RESTRICTION_CHANGES = 'CLEAR_STAGED_RESTRICTION_CHANGES';

// song trends
export const SONG_TRENDS_PENDING = 'SONG_TRENDS_PENDING';
export const SONG_TRENDS_SUCCESS = 'SONG_TRENDS_SUCCESS';
export const SONG_TRENDS_FAILURE = 'SONG_TRENDS_FAILURE';
export const SET_TRENDS_COLUMNS = 'SET_TRENDS_COLUMNS';
export const TOGGLE_TRENDS = 'TOGGLE_TRENDS';
export const SET_TRENDS = 'SET_TRENDS';

// packets
export const PACKET_PENDING = 'PACKET_PENDING';
export const PACKET_SUCCESS = 'PACKET_SUCCESS';
export const PACKET_FAILURE = 'PACKET_FAILURE';

// category highlight
export const HIGHLIGHT_CATEGORY_VERSION = 'HIGHLIGHT_CATEGORY_VERSION';
export const DEHIGHLIGHT_CATEGORY_VERSION = 'DEHIGHLIGHT_CATEGORY_VERSION';

// category sidebar
export const ON_SET_SONG_INFO_SELECTED = 'ON_SET_SONG_INFO_SELECTED';

// board groups
export const REQUEST_BOARDGROUPS = 'REQUEST_BOARDGROUPS';
export const RECEIVE_BOARDGROUPS = 'RECEIVE_BOARDGROUPS';
export const COMMIT_BOARDGROUPS = 'COMMIT_BOARDGROUPS';
export const THROW_BOARDGROUPS = 'THROW_BOARDGROUPS';

// MT overlay
export const REQUEST_OVERLAY = 'REQUEST_OVERLAY';
export const SUCCESS_REQUEST_OVERLAY = 'SUCCESS_REQUEST_OVERLAY';
export const ERROR_REQUEST_OVERLAY = 'ERROR_REQUEST_OVERLAY';
export const SUCCESS_APPROVE_OVERLAY = 'SUCCESS_APPROVE_OVERLAY';
export const ERROR_APPROVE_OVERLAY = 'ERROR_APPROVE_OVERLAY';
export const SUCCESS_CANCEL_OVERLAY = 'SUCCESS_CANCEL_OVERLAY';
export const ERROR_CANCEL_OVERLAY = 'ERROR_CANCEL_OVERLAY';
export const CLOSE_OVERLAY = 'CLOSE_OVERLAY';
export const OPEN_OVERLAY = 'OPEN_OVERLAY';
export const RESET_ERROR = 'RESET_ERROR';

// recat reasons
export const REQUEST_REASONS = 'REQUEST_REASONS';
export const RECEIVE_REASONS = 'RECEIVE_REASONS';
export const THROW_REASONS = 'THROW_REASONS';

// song versions
export const SONG_VERSIONS_PENDING = 'SONG_VERSIONS_PENDING';
export const SONG_VERSIONS_SUCCESS = 'SONG_VERSIONS_SUCCESS';
export const SONG_VERSIONS_FAILURE = 'SONG_VERSIONS_FAILURE';
export const UPDATE_VERSION_CATEGORY = 'UPDATE_VERSION_CATEGORY';
export const CLEAR_VERSION_CATEGORIES = 'CLEAR_VERSION_CATEGORIES';
export const CLEAR_STAGED_CHANGES = 'CLEAR_STAGED_CHANGES';
export const STAGE_SONGS_MEDIA = 'STAGE_SONGS_MEDIA';
export const CLEAR_VERSION_CATEGORIES_SUCCESS = 'CLEAR_VERSION_CATEGORIES_SUCCESS';
export const CLEAR_VERSION_CATEGORIES_FAILURE = 'CLEAR_VERSION_CATEGORIES_FAILURE';
export const CLEAR_CHANGES_UNDONE = 'CLEAR_CHANGES_UNDONE';

// song competitor spins
export const SONG_COMPETITOR_SPINS_PENDING = 'SONG_COMPETITOR_SPINS_PENDING';
export const SONG_COMPETITOR_SPINS_SUCCESS = 'SONG_COMPETITOR_SPINS_SUCCESS';
export const SONG_COMPETITOR_SPINS_FAILURE = 'SONG_COMPETITOR_SPINS_FAILURE';

// songs
export const SONGS_PENDING = 'SONGS_PENDING';
export const SONGS_SUCCESS = 'SONGS_SUCCESS';
export const SONGS_FAILURE = 'SONGS_FAILURE';
export const SET_SONGS = 'SET_SONGS';
export const SONG_LOAD_IN_PROGRESS = 'SONG_LOAD_IN_PROGRESS';

// similar stations
export const SIMILAR_STATIONS_PENDING = 'SIMILAR_STATIONS_PENDING';
export const SIMILAR_STATIONS_SUCCESS = 'SIMILAR_STATIONS_SUCCESS';
export const SIMILAR_STATIONS_FAILURE = 'SIMILAR_STATIONS_FAILURE';
export const CLOSE_SIMILAR_STATIONS = 'CLOSE_SIMILAR_STATIONS';

// category
export const CATEGORIES_PENDING = 'CATEGORIES_PENDING';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const SIDERAIL_ACTION = 'SIDERAIL_ACTION';

// breakout
export const UPDATE_BREAKOUT_DETAILS = 'UPDATE_BREAKOUT_DETAILS';
export const REQUEST_BREAKOUT_DATA = 'REQUEST_BREAKOUT_DATA';

// breakout preferences
export const BREAKOUT_PREF_SUCCESS = 'BREAKOUT_PREF_SUCCESS';
export const BREAKOUT_PREF_FAIL = 'BREAKOUT_PREF_FAIL';

// date integrity
export const STORE_BOARD_METADATA = 'STORE_BOARD_METADATA';
export const RECEIVE_BOARD_METADATA = 'RECEIVE_BOARD_METADATA';

// features
export const LOAD_SYSTEM_FEATURES = 'LOAD_SYSTEM_FEATURES';
export const LOAD_STATION_FEATURES = 'LOAD_STATION_FEATURES';

// lookup tables
export const REQUEST_FORMATS = 'REQUEST_FORMATS';
export const RECEIVE_FORMATS = 'RECEIVE_FORMATS';
export const THROW_FORMATS = 'THROW_FORMATS';
export const REQUEST_MARKETS = 'REQUEST_MARKETS';
export const RECEIVE_MARKETS = 'RECEIVE_MARKETS';
export const THROW_MARKETS = 'THROW_MARKETS';

// music tracker
export const ON_SET_DATE = 'ON_SET_DATE';
export const UPDATE_COMPARE_OPTIONS = 'UPDATE_COMPARE_OPTIONS';
export const ON_SET_FILTER = 'ON_SET_FILTER';
export const ON_RESET_FILTER = 'ON_RESET_FILTER';
export const REMOVE_READ_ONLY_CATEGORIES = 'REMOVE_READ_ONLY_CATEGORIES';

// music tracker data
export const GET_MUSIC_TRACKER_DATA = 'GET_MUSIC_TRACKER_DATA';
export const STORE_STATION_CATEGORY = 'STORE_STATION_CATEGORY';
export const STORE_CATEGORY_DATASET = 'STORE_CATEGORY_DATASET';
export const LOADING_CATEGORY_DETAILS = 'LOADING_CATEGORY_DETAILS';
export const CLOSE_CATEGORY_DETAILS = 'CLOSE_CATEGORY_DETAILS';

// preferences
export const LOAD_SETTINGS_DONE = 'LOAD_SETTINGS_DONE';
export const LOAD_SETTINGS_START = 'LOAD_SETTINGS_START';
export const LOAD_SETTINGS_FAIL = 'LOAD_SETTINGS_FAIL';
export const ON_APPLY = 'ON_APPLY';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

// radio board filters
export const STORE_RADIOBOARD_FILTERS = 'STORE_RADIOBOARD_FILTERS';

// user
export const USER_LOGIN = 'USER_LOGIN';
export const STORE_MUSIC_TRACKER_PREFERENCES = 'STORE_MUSIC_TRACKER_PREFERENCES';

// station info
export const REQUEST_STATIONS_INFO = 'REQUEST_STATIONS_INFO';
export const SUCCESS_STATIONS_INFO = 'SUCCESS_STATIONS_INFO';
export const FAILURE_STATIONS_INFO = 'FAILURE_STATIONS_INFO';
export const SET_CURRENT_STATION = 'SET_CURRENT_STATION';

// new preferences
export const SUCCESS_TABLE_PREFERENCES = 'SUCCESS_TABLE_PREFERENCES';

// song metadata
export const SUCCESS_SONG_METADATA = 'SUCCESS_SONG_METADATA';

// cmm
export const CALLOUT_PENDING = 'CALLOUT_PENDING';
export const CALLOUT_SUCCESS = 'CALLOUT_SUCCESS';
export const CALLOUT_FAILURE = 'CALLOUT_FAILURE';
export const OMT_PENDING = 'OMT_PENDING';
export const OMT_SUCCESS = 'OMT_SUCCESS';
export const OMT_FAILURE = 'OMT_FAILURE';
export const CC_CALLOUT_PENDING = 'CC_CALLOUT_PENDING';
export const CC_CALLOUT_SUCCESS = 'CC_CALLOUT_SUCCESS';
export const CC_CALLOUT_FAILURE = 'CC_CALLOUT_FAILURE';
export const CC_OMT_PENDING = 'CC_OMT_PENDING';
export const CC_OMT_SUCCESS = 'CC_OMT_SUCCESS';
export const CC_OMT_FAILURE = 'CC_OMT_FAILURE';

// cmm Trends
export const CALLOUT_TRENDS_PENDING = 'CALLOUT_TRENDS_PENDING';
export const CALLOUT_TRENDS_SUCCESS = 'CALLOUT_TRENDS_SUCCESS';
export const CALLOUT_TRENDS_FAILURE = 'CALLOUT_TRENDS_FAILURE';
export const OMT_TRENDS_PENDING = 'OMT_TRENDS_PENDING';
export const OMT_TRENDS_SUCCESS = 'OMT_TRENDS_SUCCESS';
export const OMT_TRENDS_FAILURE = 'OMT_TRENDS_FAILURE';
export const CC_CALLOUT_TRENDS_PENDING = 'CC_CALLOUT_TRENDS_PENDING';
export const CC_CALLOUT_TRENDS_SUCCESS = 'CC_CALLOUT_TRENDS_SUCCESS';
export const CC_CALLOUT_TRENDS_FAILURE = 'CC_CALLOUT_TRENDS_FAILURE';
export const CC_OMT_TRENDS_PENDING = 'CC_OMT_TRENDS_PENDING';
export const CC_OMT_TRENDS_SUCCESS = 'CC_OMT_TRENDS_SUCCESS';
export const CC_OMT_TRENDS_FAILURE = 'CC_OMT_TRENDS_FAILURE';

// categories metadata
export const CATEGORIES_METADATA_PENDING = 'CATEGORIES_METADATA_PENDING';
export const CATEGORIES_METADATA_SUCCESS = 'CATEGORIES_METADATA_SUCCESS';
export const CATEGORIES_METADATA_FAILURE = 'CATEGORIES_METADATA_FAILURE';

// station categories
export const STATION_CATEGORIES_PENDING = 'STATION_CATEGORIES_PENDING';
export const STATION_CATEGORIES_SUCCESS = 'STATION_CATEGORIES_SUCCESS';
export const STATION_CATEGORIES_FAILURE = 'STATION_CATEGORIES_FAILURE';
